permalink: /:title/
description: "Writings from David and Suzi Chang. A story of redemption and faith."

google_analytics: UA-35626315-1
comments: true

twitter_username: davidchizzle
twitter_image: https://pbs.twimg.com/profile_images/535137081693970432/3oGBgOqS_400x400.jpeg
