permalink: /:title/
description: "Writings from David and Suzi Chang. A story of redemption and faith."
theme: jekyll-whiteglass

plugins:
  - jekyll-sitemap

google_analytics: UA-35626315-1
comments: true
